name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: ./ci_install.sh

    - name: "Build → armeabi-v7a"
      run: |
        . env.sh
        ./build.sh --all armeabi-v7a

    - name: "Build → arm64-v8a"
      run: |
        . env.sh
        ./build.sh --all arm64-v8a

    - name: Archive
      run: |
        cd deps && zip -9r ../deps.zip -- *
        ls -lh ../deps.zip

    - name: Upload and tag
      uses: pyTooling/Actions/releaser@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'latest'
        files: ./deps.zip
      if: github.event_name != 'pull_request'
